language: c
sudo: false

env:
  - STACK_YAML=stack-lts-2.yaml   UPDATE_NIGHTLY=NO
  - STACK_YAML=stack-lts-3.yaml   UPDATE_NIGHTLY=NO
  - STACK_YAML=stack-lts-6.yaml   UPDATE_NIGHTLY=NO
  - STACK_YAML=stack-lts-7.yaml   UPDATE_NIGHTLY=NO
  - STACK_YAML=stack-lts-8.yaml   UPDATE_NIGHTLY=NO
  - STACK_YAML=stack-lts-9.yaml   UPDATE_NIGHTLY=NO
  - STACK_YAML=stack.yaml         UPDATE_NIGHTLY=NO
  - STACK_YAML=stack-nightly.yaml UPDATE_NIGHTLY=YES

addons:
  apt:
    packages:
      - libgmp-dev

matrix:
  allow_failures:
    - env: STACK_YAML=stack-nightly.yaml UPDATE_NIGHTLY=YES

cache:
  directories:
    - $HOME/.stack/

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - ./tools/update_nightly.sh
  - stack setup --no-terminal
  - stack ghc -- --version

script:
  - stack --no-terminal test
  - LD_LIBRARY_PATH="libsass/lib" stack --no-terminal test --flag hlibsass:sharedlibsass
